container:
  image: ubuntu:bionic

task:
  matrix:
    - name: Build (gcc, Release)
      install_dependencies_script:
        - wget https://github.com/Kitware/CMake/releases/download/v3.21.0/cmake-3.21.0-linux-x86_64.sh -qO cmake.sh && sh cmake.sh --skip-license --prefix=/usr
      script: ./ci/run_tests.sh -DCMAKE_BUILD_TYPE=Release
      container:
        matrix:
          - image: gcc:11
          - image: gcc:10
          - image: gcc:9
          - image: gcc:8
          - image: gcc:7
          # - image: gcc:6
          # - image: gcc:5
          # - image: gcc:4.9
          # - image: gcc:4.8
    - name: Build (gcc, Debug)
      install_dependencies_script:
        - wget https://github.com/Kitware/CMake/releases/download/v3.21.0/cmake-3.21.0-linux-x86_64.sh -qO cmake.sh && sh cmake.sh --skip-license --prefix=/usr
      script: ./ci/run_tests.sh -DCMAKE_BUILD_TYPE=Debug
      container:
        matrix:
          - image: gcc:11
          - image: gcc:10
          - image: gcc:9
          - image: gcc:8
          - image: gcc:7
          - image: gcc:6
          - image: gcc:5
          - image: gcc:4.9
          - image: gcc:4.8
    - name: Build (clang, Release)
      install_dependencies_script:
        - apt-get update
        - wget https://github.com/Kitware/CMake/releases/download/v3.21.0/cmake-3.21.0-linux-x86_64.sh -qO cmake.sh && sh cmake.sh --skip-license --prefix=/usr
      script: ./ci/run_tests.sh -DCMAKE_BUILD_TYPE=Release -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++
      container:
        matrix:
          - image: silkeh/clang:11
          - image: silkeh/clang:10
          - image: silkeh/clang:9
          - image: silkeh/clang:8
          - image: silkeh/clang:7
          - image: silkeh/clang:6
          - image: silkeh/clang:5
          - image: silkeh/clang:4
    - name: Build (clang, Debug)
      install_dependencies_script:
        - apt-get update
        - wget https://github.com/Kitware/CMake/releases/download/v3.21.0/cmake-3.21.0-linux-x86_64.sh -qO cmake.sh && sh cmake.sh --skip-license --prefix=/usr
      script: ./ci/run_tests.sh -DCMAKE_BUILD_TYPE=Debug -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++
      container:
        matrix:
          - image: silkeh/clang:11
          - image: silkeh/clang:10
          - image: silkeh/clang:9
          - image: silkeh/clang:8
          - image: silkeh/clang:7
          - image: silkeh/clang:6
          - image: silkeh/clang:5
          - image: silkeh/clang:4          
    - name: Build (gcc, Debug, ASAN)
      install_dependencies_script:
        - apt-get update
        - apt-get install -y cmake gcc g++
      script: ./ci/run_tests.sh -DCMAKE_BUILD_TYPE=ASanDebug
      container:
        matrix:
          - image: ubuntu:20.04
          - image: ubuntu:16.04
          - image: ubuntu:18.04
    - name: Build (gcc, Debug, TSAN)
      only_if: $CIRRUS_BRANCH == 'master' || $CIRRUS_TAG != '' || $CIRRUS_PR != ''
      install_dependencies_script:
        - apt-get update
        - apt-get install -y cmake gcc g++
      script: TIMEOUT=3600 ./ci/run_tests.sh -DCMAKE_BUILD_TYPE=TSanDebug
      container:
        matrix:
          - image: ubuntu:20.04
          - image: ubuntu:16.04
          - image: ubuntu:18.04
    - name: Build (gcc, Release, ASAN)
      install_dependencies_script:
        - apt-get update
        - apt-get install -y cmake gcc g++
      script: ./ci/run_tests.sh -DCMAKE_BUILD_TYPE=ASan
      container:
        matrix:
          - image: ubuntu:20.04
          - image: ubuntu:16.04
          - image: ubuntu:18.04
    - name: Build (gcc, Release, TSAN)
      only_if: $CIRRUS_BRANCH == 'master' || $CIRRUS_TAG != '' || $CIRRUS_PR != ''
      install_dependencies_script:
        - apt-get update
        - apt-get install -y cmake gcc g++
      script: TIMEOUT=3600 ./ci/run_tests.sh -DCMAKE_BUILD_TYPE=TSan
      container:
        matrix:
          - image: ubuntu:20.04
          - image: ubuntu:16.04
          - image: ubuntu:18.04
